# Generated by Django 4.2.16 on 2026-05-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('schedule_docx', 'Расписание врача (DOCX)'), ('feedback_xlsx', 'Отчёт по заявкам (XLSX)'), ('appointment_docx', 'Справка о записи (DOCX)')], max_length=30, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметры генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
