# Generated by Django 4.2.16 on 2026-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='beds_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество коек'),
        ),
        migrations.AddField(
            model_name='department',
            name='extra_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
