# Generated by Django 4.2.16 on 2026-05-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_department_beds_count_department_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='patient_memos/%Y/%m/', verbose_name='Файл-памятка'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='patient_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='hospital.patientinfo', verbose_name='Материал для пациентов'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
    ]
